import Carousel from './Carousel.js';
import Vercarousel from './Vercarousel.js';
import Accordion from './Accordion.js';
import GenPassword from './GenPassword.js';
import ScreenLightController from './ScreenLightController.js';
import ModalWindow from './ModalWindow.js';
import Notice from './Animation.js';
import ToDoList from './ToDoList.js';
import Tabs from './Tabs.js';
import Slider from './Slider.js';

new Carousel();
new Vercarousel();
new Accordion();
new GenPassword();
new ScreenLightController();
new ModalWindow();
new ToDoList();
new Notice();
new Tabs();
new Slider();